### ISSUE TITLE
Fix online CustDoc link to Looking Up Connection Factories from LDAP-Based JNDI Stores

### ISSUE THREAD

**Issue by bczoma** [SolaceSamples/solace-samples-jms#11]
docs-jms-establishing-connections: http://docs.solace.com/Solace-JMS-API/Obtaining-Connection-Fac.htm#establishing_connections_577400906_317143

This link will break easily. Should work with Solace docs team to get a permanent link to this location.

**Comment by Mrc0113** [comment]
Closing. Any broken links have been fixed with the new tutorials site and automatic link checking runs on a set schedule.
