### ISSUE TITLE
Improve JNDI Connection factory lookup in JNDI Tutorial

### ISSUE THREAD

**Issue by mdspielman** [SolaceSamples/solace-samples-jms#12]
In https://solacesamples.github.io/solace-samples-jms/using-jndi/, the tutorial shows how to lookup a connection factory and outlines:

env.put(Context.SECURITY_PRINCIPAL, "clientUsername");
env.put(SupportedProperty.SOLACE_JMS_VPN, "default");

This can be simplified to:

env.put(Context.SECURITY_PRINCIPAL, "clientUsername@default");

And this nicely avoids a proprietary Solace JMS property.

**Comment by yesitskuldeep** [comment]
i am running this command 
./build/staged/bin/queueConsumerJNDI 155.178.68.48:55555 degatech@FDPS 7ErZkG2Us7g1EfM
and getting this error
QueueConsumerJNDI is connecting to Solace messaging at 155.178.68.48:55555...
Nov 17, 2017 12:22:38 PM com.solacesystems.jcsmp.protocol.impl.TcpClientChannel call
INFO: Connecting to host 'orig=tcp://155.178.68.48:55555, scheme=tcp://, host=155.178.68.48, port=55555' (host 1 of 1, smfclient 2, attempt 1 of 1, this_host_attempt: 1 of 1)
Nov 17, 2017 12:22:38 PM com.solacesystems.jcsmp.protocol.impl.TcpClientChannel call
INFO: Connected to host 'orig=tcp://155.178.68.48:55555, scheme=tcp://, host=155.178.68.48, port=55555' (smfclient 2)
Nov 17, 2017 12:22:39 PM com.solacesystems.jcsmp.protocol.impl.TcpClientChannel close
INFO: Channel Closed (smfclient 2)
Nov 17, 2017 12:22:39 PM com.solacesystems.jcsmp.protocol.impl.TcpClientChannel call
INFO: Connecting to host 'orig=tcp://155.178.68.48:55555, scheme=tcp://, host=155.178.68.48, port=55555' (host 1 of 1, smfclient 4, attempt 1 of 2147483647, this_host_attempt: 1 of 1)
Nov 17, 2017 12:22:39 PM com.solacesystems.jcsmp.protocol.impl.TcpClientChannel call
INFO: Connection attempt failed to host '155.178.68.48' ConnectException com.solacesystems.jcsmp.JCSMPTransportException: (Client name: ip-172-31-8-135/17161/#000a0002   Local addr: 10.0.8.2:50434   Remote addr: 155.178.68.48:55555) - Error communicating with the router. cause: java.io.IOException: Stream error (zlib). ((Client name: ip-172-31-8-135/17161/#000a0002   Local addr: 10.0.8.2:50434   Remote addr: 155.178.68.48:55555) - )



Kindly help me in this regard.

**Comment by mdspielman** [comment]
@yesitskuldeep, this kind of questions for help is best posted on  https://stackoverflow.com/questions/tagged/solace. There you can get a specific answer for your question. If there is an issue with the tutorials that should be fixed, please do raise a new issue.

**Comment by Mrc0113** [comment]
Closing - this was previously resolved.
