### ISSUE TITLE
403: Message VPN Not Allowed

### ISSUE THREAD

**Issue by bkhbea** [SolaceSamples/solace-samples-jms#39]
Have Solace Docker image running on AWS.
    Created a Connection Factory and a Topic
    Using Solace Java API, I was able to send/receive messages using my local Eclipse
    When trying to use the standard JMS API (both Sending/Receiving), I keep getting the following message : '403: Message VPN Not Allowed'. 

403 messages as usual means forbidden. Tracing the code, the error is thrown while trying to lookup the connection factory. Looking at the cause of this error, the documentation says : " The Message VPN name set for the session is not allowed for the session's username."
    Further looking at the documentation, the following is stated " When internal authorization is used, rather than LDAP group authorization, client usernames provisioned on the Message VPN will determine a client’s authorization. If the client provides a client username that matches a client username provisioned in the Message VPN that the client has connected to, the client and ACL profiles configured for that client username are applied to the client. If the client does not provide a client username, the message broker will attempt to apply the client username named default and the client and ACL profiles configured for that client username".
    I created a new 'client username' and assigned him the default ACL profile and Client profile. The 'default' ACL profile is allowed to publish and subscribe but the error persists. 

What am I missing? Please advise

**Comment by bczoma** [comment]
Also check your Client Profile settings if sending and receiving of guaranteed messages are enabled.

**Comment by bkhbea** [comment]
Hi,

it is enabled

**Comment by bczoma** [comment]
For a quick comparison you could spin up a Solace message broker in Solace cloud where this is expected to work with the default settings:
https://cloud.solace.com/learn/group_getting_started/ggs_signup.html

**Comment by bkhbea** [comment]
I actually did exactly that and all worked just fine. I am sure I am
missing something some where ad I did compare and seems to be identical.

Docker log for Solace container is not showing any errors.

Thanks

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️
