### ISSUE TITLE
Missing underscores in code extract (display issue)

### ISSUE THREAD

**Issue by itsJamilAhmed** [SolaceSamples/solace-samples-jms#43]
In the section: "Step 3: Obtaining JMS Destination objects using JNDI" there are underscores not being displayed correctly from the code extract:

final String QUEUE_NAME = "Q/tutorial";
final String QUEUE_JNDI_NAME = "/JNDI/" + QUEUE_NAME;
Queue queue = (Queue) initialContext.lookup(QUEUE_JNDI_NAME);

But copy-paste of the text does reveal them though...
![image](https://user-images.githubusercontent.com/35374694/62121620-dd1ffb80-b2bb-11e9-8ee5-b23bf5179f65.png)

**Comment by bczoma** [comment]
This is a strange rendering issue as the underscore is indeed there in the source doc.

Giving a try to remove "java" for the code renderer to see if it fixes it.

**Comment by Mrc0113** [comment]
Resolved by https://github.com/SolaceSamples/solace-samples-jms/pull/44

**Comment by Mrc0113** [comment]
Re-opening as it seems to be a line-height issue in the formatted section.

**Comment by Mrc0113** [comment]
Closing. Resolved w/ new styling on new tutorials.solace.dev site
