### ISSUE TITLE
Update Persistence with Queues sample code to take an optional message-VPN argument.

### ISSUE THREAD

**Issue by bczoma** [SolaceSamples/solace-samples-jms#9]
This would enable to demo the results of the solace-samples-semp sample "Basic Message VPN creation with Queue". Note: the semp sample would create the new message-VPN with the username and password used by this sample.

At a minimum, QueueProducer should be updated. Tbd if QueueConsumer should be updated as well.

**Comment by mdspielman** [comment]
Fixed by pull request #10.
